HelloWorld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="Hello"),
    path("<str:name>", views.greet, name="greet"),
    path("suman", views.suman, name="suman")
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("", views.index, name="newyearindex")
]

tasks/urls.py
from django.urls import path

from . import views
app_name ="tasks"
urlpatterns =[
    path("",views.index, name= "index"),
    path("add", views.add, name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

def suman(request):
    return HttpResponse("hello, suman")

newyear/views.py
from django.shortcuts import render
import datetime
now = datetime.datetime.now()

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.day==1 and now.month==1
    })

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

# tasks = []

class NewTaskForm(forms.Form):
    task= forms.CharField(label="New Task")
# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] =[]
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    #server side validation
    if request.method == "POST":
        form = NewTaskForm(request.POST) #this gets the submitted value of form
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"]+=[task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form":form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>greeting</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       <h1> hello {{name}}</h1>
    </body>
</html>

hello/templates/hello/index.html
<<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>suman</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <h1> hello world</h1>
        
        <script src="" async defer></script>
    </body>
</html>

newyear/templates/newyear/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
{%load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Is it New Year?</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
    </head>
    <body>
       {% if newyear %}
            <h1>YES</h>
       {% else %}
            <h1>NO</h1>
       {% endif %}
        
    </body>
</html>

tasks/templates/tasks/add.html
 {% extends "tasks/layout.html" %}
{%block body%}
 <h1> Add taks</h1>
        <form action="{% url 'tasks:add' %}" method=post>
        {% csrf_token %}
           {{form}}
            <input type= "submit">
        </form>
<a href="{% url 'tasks:index' %}"> go to tasks</a>
{%endblock%}

tasks/templates/tasks/index.html
{%  extends "tasks/layout.html" %}
{%block body%}
<h1>tasks</h1>
<ul>
    {%for task in tasks%}
        <li>{{task}}</li>
    {% empty %}
        <li> no task</li>
    {%endfor%}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a>

{%endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Tasks</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       {% block body %}
       {%endblock%}
    </body>
</html>